//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Login.rc
//
#define IDD_PROPPAGE_SRVMAN             102
#define IDW_LOGIN                       1000
#define IDC_BTN_GUIDE                   1001
#define IDC_RAD_HQJY                    1002
#define IDC_RAD_JY                      1003
#define IDC_RAD_HQ                      1004
#define IDC_BTN_COMM                    1005
#define IDC_BTN_TEST                    1006
#define IDC_BTN_TUOJI                   1007
#define IDC_BTN_LOGIN                   1008
#define IDC_BTN_EXIT                    1009
#define IDC_STC_INPUTZONE               1010
#define IDC_STC_PROGRESS                1011
#define IDW_JY_INPUT                    1012
#define IDC_CMB_1                       1013
#define IDC_CMB_2                       1014
#define IDC_CHK_1                       1015
#define IDC_CMO_ACCOUNT                 1016
#define IDC_CHK_2                       1017
#define IDC_EDT_JYPWD                   1018
#define IDC_EDT_VALIDATE                1019
#define IDC_STC_VALIDATE                1020
#define IDC_STA_4                       1021
#define IDC_STA_5                       1022
#define IDC_STA_6                       1023
#define IDC_STA_7                       1024
#define IDC_STA_8                       1025
#define IDC_STA_9                       1026
#define IDD_DIALOG_LOGIN                6000
#define IDB_BITMAP2                     6001
#define IDD_PROPPAGE_PROXYMAN           6001
#define IDC_COMBO1                      6003
#define IDC_COMBO_AccountType           6003
#define IDC_COMBO2                      6004
#define IDC_COMBO_Cell                  6004
#define IDB_BITMAP3                     6005
#define IDD_DIALOG_SRV_SET              6006
#define IDC_COMBO_ACCOUNT               6006
#define IDD_DIALOG_SPEEDTEST            6007
#define IDC_EDIT_PWD                    6008
#define IDD_DIALOG_JY                   6008
#define IDC_EDIT_VALIDATE               6009
#define IDD_DIALOG_LEVELINPUT           6009
#define IDD_PROPPAGE_LEVEL              6010
#define IDC_BUTTON_LOGIN                6011
#define IDD_DIALOG1                     6011
#define IDD_DIALOG_FRAME                6011
#define IDD_DIALOG_LEVELFRAME           6011
#define IDC_BUTTON_TUOJI                6012
#define IDS_STRING_JYNow                6012
#define IDC_BUTTON_GUIDE                6013
#define IDS_STRING_JYSuccess            6013
#define IDC_BUTTON_COMM                 6014
#define IDS_STRING_JYFail               6014
#define IDC_BUTTON_TEST                 6015
#define IDS_STRING_QuoteFail            6015
#define IDB_BITMAP1                     6015
#define IDC_RADIO_HQJY                  6016
#define IDS_STRING_QuoteNow             6016
#define IDC_RADIO_JY                    6017
#define IDS_STRING_AccountError         6017
#define IDC_RADIO_HQ                    6018
#define IDS_STRING_PasswardError        6018
#define IDS_STRING_ValidateError        6019
#define IDC_LIST_SRV                    6020
#define IDS_STRING_JYServerFail         6020
#define IDC_BUTTON_DEFAULT              6021
#define IDS_STRING_Error                6021
#define IDC_BUTTON_ADD                  6022
#define IDS_STRING_SrvNameNone          6022
#define IDC_BUTTON_MODIFY               6023
#define IDS_STRING_SrvIPNone            6023
#define IDC_BUTTON_DEL                  6024
#define IDS_STRING_SrvPortNone          6024
#define IDC_CHECK_AUTO                  6025
#define IDS_STRING_SrvNameRepeart       6025
#define IDC_CHECK_PROXY                 6026
#define IDS_STRING_ProxySuccess         6026
#define IDC_CHECK_CHENNAL               6027
#define IDS_STRING_ProxyFail            6027
#define IDS_STRING_ProxyTest            6028
#define IDS_STRING_ProxyNameNone        6029
#define IDC_EDIT_PORT                   6030
#define IDS_STRING_ProxyPortNone        6030
#define IDC_RADIO_HTTP                  6031
#define IDS_STRING_ProxyKindNone        6031
#define IDC_RADIO_SOCKET4               6032
#define IDS_STRING_EditQuoteNameNone    6032
#define IDC_RADIO_SOCKET5               6033
#define IDS_STRING_DeleteQutoNameNone   6033
#define IDC_EDIT_USER                   6034
#define IDS_STRING_Level2Now            6034
#define IDS_STRING_Level2Fail           6035
#define IDC_EDIT_NAME                   6036
#define IDS_STRING_Level2AccOrPWDERR    6036
#define IDS_STRING_KeyboardInit         6037
#define IDC_TAB_SPEET                   6038
#define IDS_STRING_KeyboardFinish       6038
#define IDC_LIST_TEST                   6039
#define IDS_STRING_FutureFail           6039
#define IDS_STRING_FutureNow            6040
#define IDC_STATIC_VALIDATE             6045
#define IDC_EDIT_JYPWD                  6046
#define IDC_CHECK_HIDENO                6048
#define IDC_CHECK_REMEMBER              6049
#define IDC_STATIC_INPUTZONE            6050
#define IDC_EDIT_SHACC_PAGE             6055
#define IDC_EDIT_SZACC_PAGE             6057
#define IDC_EDIT_SZPWD                  6058
#define IDC_EDIT_SHPWD                  6059
#define IDC_EDIT_SHACC                  6062
#define IDC_EDIT_SZACC                  6063
#define IDC_EDIT_SHPWD_PAGE             6064
#define IDC_EDIT_SZPWD_PAGE             6065
#define IDC_STATIC_PROGRESS             6066
#define IDC_BUTTON_SoftKeyboard         6093
#define IDC_IPADDRESS1                  6094
#define IDC_IPADDR                      6094
#define IDC_EDIT_IP                     6094
#define IDC_BUTTON2                     6096
#define IDC_BTN_CANCEL                  6096
#define IDC_STC_ZONE                    6097
#define IDC_ST_ACCOUNT                  6098
#define IDC_EDIT2                       6100
#define IDC_EDIT_ADDR                   6100
#define IDC_BUTTON1                     6101

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        6016
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         6102
#define _APS_NEXT_SYMED_VALUE           6000
#endif
#endif
