//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by DiagramRTable.rc
//
#define IDC_ED_CONTENT                  2000
#define IDD_MARK_CONTENT                2007
#define IDC_BLOCK_LIST                  3000
#define IDC_REFRESH                     3001
#define IDD_BLOCK_ADSCRIPTION           3004
#define IDC_TABITEM                     4000
#define IDC_TABGROUP                    4001
#define IDC_ADD_TO_CURRENT              4002
#define IDC_ALL_COLGROUP                4002
#define IDC_DEL_FROM_CURRENT            4003
#define IDC_COLGROUP                    4003
#define IDC_DELETEALL                   4004
#define IDD_QUOTE_COLUMN_SETTING        4004
#define IDC_SAVE_CURGROUP               4005
#define IDD_QUOTE_TAB_SETTING           4005
#define IDC_GROUPNAME                   4006
#define IDC_ADDTOCURRENT                4006
#define IDC_ADDALLTOCURRENT             4007
#define IDC_DELFROMCURRENT              4008
#define IDC_DELALLFROMCURRENT           4009
#define IDC_SAVEAS_CURGROUP             4011
#define IDC_ALLTABITEM                  4012
#define IDD_NEW_TAB_GROUP               4013
#define IDC_DEL_CUR_DISPCOL_GROUP       4013
#define IDC_NEW_GROUP                   4014
#define IDC_NEW_COLUMN                  4014
#define IDC_RESTOR_CURGROUP             4015
#define IDC_DEL_COLUMN                  4015
#define IDC_DEL_CURGROUP                4016
#define IDC_COLUMN_PROPERTY             4016
#define IDC_UP                          4017
#define IDC_CURCOLUMN                   4018
#define IDC_ALL_COLUMN                  4019
#define IDC_DOWN                        4020
#define IDS_STRING_NUM1                 6000
#define IDS_STRING_NUM2                 6001
#define IDS_STRING_NUM3                 6002
#define IDS_STRING_NUM4                 6003
#define IDS_STRING_NUM5                 6004
#define IDS_STRING_NUM6                 6005
#define IDS_STRING_NUM7                 6006
#define IDS_STRING_NUM8                 6007
#define IDS_STRING_NUM9                 6008
#define IDS_STRING_NUM10                6009
#define IDS_STRING_BUY                  6010
#define IDS_STRING_SELL                 6011
#define IDS_STRING_BUYAVG               6012
#define IDS_STRING_SELLAVG              6013
#define IDS_STRING_BUYTOTAL             6014
#define IDS_STRING_SELLTOTAL            6015
#define IDS_STRING_WEIBI                6016
#define IDS_STRING_WEICHA               6017
#define IDS_STRING_CHENGJIAO            6018
#define IDS_STRING_ZHANGDIE             6019
#define IDS_STRING_FUDU                 6020
#define IDS_STRING_ZONGSHOU             6021
#define IDS_STRING_XIANSHOU             6022
#define IDS_STRING_ZONGE                6023
#define IDS_STRING_WAIPAN               6024
#define IDS_STRING_ZHANGTING            6025
#define IDS_STRING_SHIYING              6026
#define IDS_STRING_LIUTONG              6027
#define IDS_STRING_SHIZHI               6028
#define IDS_STRING_JUNJIA               6029
#define IDS_STRING_KAIPAN               6030
#define IDS_STRING_ZUIGAO               6031
#define IDS_STRING_ZUIDI                6032
#define IDS_STRING_LIANGBI              6033
#define IDS_STRING_HUANSHOU             6034
#define IDS_STRING_NEIPAN               6035
#define IDS_STRING_DIETING              6036
#define IDS_STRING_SHIJING              6037
#define IDS_STRING_ZONGGU               6038
#define IDS_STRING_ZONGZHI              6039
#define IDS_STRING_LIXI                 6040
#define IDS_STRING_QUANJIA              6041
#define IDS_STRING_JINGZHI              6042
#define IDS_STRING_IOPV                 6043
#define IDS_STRING_ZHANGFU              6044
#define IDS_STRING_JINE                 6045
#define IDS_STRING_BUYSHOUSHU           6046
#define IDS_STRING_SELLSHSOUSHU         6047
#define IDS_STRING_SHANGZHANGJIASHU     6048
#define IDS_STRING_XIADIEJIASHU         6049
#define IDS_STRING_PINGPANJIASHU        6050
#define IDS_STRING_ZUOSHOU              6051
#define IDS_STRING_ZHENFU               6052
#define IDS_STRING_FENJIABIAO           6053
#define IDS_STRING_CHENGJIAOJIA         6054
#define IDS_STRING_CHENGJIAOLIANG       6055
#define IDS_STRING_BILI                 6056
#define IDS_STRING_LIUTONGPAN           6057
#define IDS_STRING_ZONGJINE             6058
#define IDS_STRING_CHENGJIAOBISHU       6059
#define IDS_STRING_MEIBIJUNLIANG        6060
#define IDS_STRING_MEIBIJUNE            6061
#define IDS_STRING_FENZHONGJUNLIANG     6062
#define IDS_STRING_FENZHONGJUNE         6063
#define IDS_STRING_TENJUNZHI            6064
#define IDS_STRING_TWENTYJUNZHI         6065
#define IDS_STRING_FIFTYJUNZHI          6066
#define IDS_STRING_MONTHMAX             6067
#define IDS_STRING_MONTHMIN             6068
#define IDS_STRING_YEARMAX              6069
#define IDS_STRING_YEARMIN              6070
#define IDS_STRING_SELFBLOCK            6071
#define IDS_STRING_ZONGBI               6072
#define IDS_STRING_MEIBI                6073
#define IDS_STRING_QUICKBUY             6074
#define IDS_STRING_QUICKSELL            6075
#define IDS_STRING_SELLPRICE            6076
#define IDS_STRING_BUYPRICE             6077
#define IDS_STRING_NEW                  6078
#define IDS_STRING_JIESUAN              6079
#define IDS_STRING_ZONGCHI              6080
#define IDS_STRING_SELLCOUNT            6081
#define IDS_STRING_BUYCOUNT             6082
#define IDS_STRING_QIANJIE              6083
#define IDS_STRING_RIZENG               6084

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        7002
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         7000
#define _APS_NEXT_SYMED_VALUE           7006
#endif
#endif
