//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by CompMan.rc
//
#define IDD_ADD                         2
#define ID_SET                          3
#define IDCANCEL2                       3
#define IDC_OUTPUT                      3
#define IDOK2                           3
#define IDOK6                           3
#define IDD_DEL                         3
#define IDCANCEL3                       4
#define IDOK3                           4
#define IDC_VIEW                        5
#define IDCANCEL5                       6
#define IDOK4                           6
#define IDCANCEL6                       7
#define IDD_ABOUTBOX                    100
#define CG_IDD_MYDIALOGBAR              102
#define CG_ID_VIEW_MYDIALOGBAR          103
#define CG_ID_VIEW_MYDIALOGBAR1         105
#define IDC_NODROP                      106
#define IDC_SORT                        106
#define IDR_DRAGDATA                    110
#define IDR_HXCPLATYPE                  129
#define IDR_EDITMENU                    130
#define IDB_FUN_VIEW                    131
#define IDB_EXPRESS_VIEW                132
#define IDB_FUNIMAGELIST                133
#define IDR_EXPRESSMENU                 133
#define IDB_OUTIMAGELIST                134
#define IDR_SAVEMENU                    134
#define IDD_EXCHANGE_SELECT             134
#define IDD_EXCHANGE_BUY                135
#define IDD_EXCHANGE_SELL               136
#define IDD_EXCHANGE_MODEL              137
#define IDD_EXCHANGE_RESULT             138
#define IDD_FORMULAMAN                  139
#define IDB_CLOSEBTN                    140
#define IDD_ERRORDLG                    141
#define IDD_PASSWORD                    143
#define IDB_BITMAP2_EXPLOYER            151
#define IDB_BITMAP3_EXPLOYER            152
#define IDB_DRAWIMAGE                   155
#define IDD_CONDITION_STOCK             175
#define IDB_BITMAP3_PRE                 213
#define IDB_BITMAP2_PRE                 214
#define IDD_NEWUNIONDLG                 223
#define IDD_NOTEANDEIDOLON              239
#define IDB_BITMAP3_NEXT                259
#define IDB_BITMAP2_NEXT                260
#define IDB_BITMAP1_PRE                 261
#define IDB_BITMAP1_NEXT                262
#define IDB_BITMAP1_EXPLOYER            263
#define IDB_EXPRESS_TAB                 264
#define IDD_ALARM_STOCK                 289
#define IDD_ALARM_SET                   290
#define IDD_INPORTEXPORT                307
#define IDB_CHECKBOXIMG                 311
#define IDD_ALLIMAGE                    312
#define IDD_FORMULA                     314
#define IDD_ESTOPPERIOD                 338
#define IDD_FUNCTIONMAN                 339
#define IDD_ALARM_ANASIS                374
#define IDD_CONDITION_UNION             385
#define IDD_EXCHANGE_UNION              392
#define IDD_EC_LAST_PARAM_TEST          491
#define IDD_EC_LAST_INDEX               493
#define IDD_EC_SY_TEST                  496
#define IDC_EDITPASSS                   1000
#define IDC_NAMECOMBO                   1000
#define IDC_INDICATOR                   1000
#define IDC_NAMEEXPRESSION              1001
#define IDC_PROMPT                      1002
#define IDC_PWDCHECK                    1002
#define IDC_PWDEDIT                     1003
#define IDC_NOTE                        1004
#define IDC_NUMEN                       1005
#define IDC_COMPILE                     1006
#define IDC_BANPIERIODS                 1007
#define IDC_OK                          1008
#define IDC_USERHELP                    1010
#define IDC_INFUNCTION                  1014
#define IDC_ADD_STK                     1014
#define IDC_ADD_CON                     1014
#define IDB_ADD                         1014
#define IDD_DELETE                      1016
#define IDC_DEL_STK                     1016
#define IDC_DEL_CON                     1016
#define IDB_DELETE                      1016
#define IDD_DELETE2                     1017
#define IDD_SaveUnion                   1017
#define IDC_DEL_ALARM                   1017
#define IDD_LoadUnion                   1018
#define IDD_BEGINDATE                   1019
#define IDC_BEGIN_TIME                  1019
#define IDT_TIEMSTART                   1019
#define IDD_ENDDATE                     1020
#define IDC_END_TIME                    1020
#define IDT_TIMEEND                     1020
#define IDD_CONDITION_SELECTSTOCK       1020
#define IDC_STOPPERIOD                  1021
#define IDD_ENDDATE2                    1021
#define IDD_DelUnion                    1022
#define IDD_NOTES                       1023
#define IDD_PROGRESS                    1024
#define IDC_NEWEXPRESS                  1037
#define IDC_ENGTOCHINESE                1038
#define IDC_COMMENT                     1053
#define IDC_EXPRESSOUT                  1058
#define IDC_VERSION                     1059
#define IDC_EXPRESSIN                   1059
#define IDD_NEW                         1069
#define IDD_UPDATE                      1073
#define IDC_CHAGE_CON                   1073
#define IDC_NAMEEDIT                    1074
#define IDC_DESCRIBEEDIT                1075
#define IDC_NOTES                       1077
#define IDC_TAB                         1080
#define IDD_IN                          1083
#define IDD_OUT                         1084
#define IDD_TEMPIN                      1085
#define IDC_PWD                         1087
#define IDC_STATIC_GROUP                1088
#define IDC_NAME                        1089
#define IDC_PROMTEDIT                   1090
#define IDC_PARAM                       1093
#define IDC_INSERT                      1094
#define IDC_PARAM7                      1094
#define IDC_MAINCHART                   1095
#define IDC_PARAM8                      1095
#define IDC_SUBCHART                    1096
#define IDC_FUNLIST                     1097
#define IDC_EDITNOTES                   1101
#define IDC_ERROR                       1103
#define IDC_LIST                        1104
#define IDD_ADVANCE                     1156
#define IDC_MONEYC                      1163
#define IDC_MONEYC2                     1164
#define IDC_ALLBUY                      1166
#define IDC_BLOCKNAME                   1177
#define IDC_LOSE                        1184
#define IDC_BUY1                        1185
#define IDC_DOWN                        1186
#define IDC_HP                          1187
#define IDC_LOSECOUNT                   1188
#define IDC_LRCOUNT                     1189
#define IDC_DOWNCOUNT                   1190
#define IDC_DOWNBL                      1191
#define IDC_HPCOUNT                     1192
#define IDC_HPBL                        1193
#define IDD_PERIOD                      1194
#define IDC_BUY                         1194
#define IDC_BUYCOUNT                    1195
#define IDC_EDIT_EXPRESS                1199
#define IDC_EDIT_EIDOLON                1200
#define ss                              1200
#define IDC_NOTESEDIT                   1200
#define IDC_ALARM_LIST                  1219
#define IDC_FIRST_DATE                  1237
#define IDC_LSAT_DATE                   1238
#define IDC_LAST_DATE                   1238
#define IDC_LASE_DATE                   1238
#define IDC_DEFAXISEDIT                 1241
#define IDC_IDERPWDSTR                  1241
#define IDD_DATA1                       1258
#define IDC_COMCON2                     1258
#define IDD_DATA2                       1278
#define IDC_COMCON3                     1278
#define IDD_AND                         1301
#define IDD_OR                          1302
#define IDD_TYPE                        1308
#define IDD_FUNLIST                     1309
#define IDD_NAME                        1321
#define IDB_DEFAULT                     1334
#define IDC_STK_LIST                    1335
#define IDC_                            1341
#define IDC_PERIED                      1341
#define IDC_DEFAULTPERIOD               1344
#define IDC_CON_LIST                    1349
#define IDD_CON                         1351
#define IDC_COMCOND                     1351
#define IDD_INCLUDE                     1364
#define IDC_STATICMONEY                 1372
#define IDC_STATICMONEY2                1373
#define IDC_ALL_DATA                    1374
#define IDD_USERNOTES                   1393
#define IDD_UPDATEUNION                 1395
#define IDD_NEWUNION                    1396
#define IDC_STOCKNUM                    1397
#define IDC_PARAM1                      1397
#define IDC_AMOUNT                      1399
#define IDC_PARAM2                      1399
#define IDC_FUN                         1400
#define IDC_CIRCLE                      1401
#define IDC_TEST_CAUSE                  1402
#define IDC_PARAM3                      1402
#define IDC_CAUSE                       1402
#define IDB_MODEFY                      1403
#define IDC_BLOCK_LIST                  1405
#define IDC_PRESS                       1406
#define IDC_COMUSE                      1407
#define IDC_OVERING                     1407
#define IDC_PARAM4                      1407
#define IDC_RESULT                      1409
#define IDC_STATE                       1409
#define IDC_DEL_MONEY                   1410
#define IDC_ADD_MONEY                   1411
#define IDC_TOTAL                       1416
#define IDC_APPOINT_DATA                1420
#define IDC_APPOINT_DATE                1420
#define IDC_ALLDATE                     1422
#define IDC_WARNING                     1427
#define IDC_PARAM5                      1432
#define IDC_PARAM6                      1433
#define IDC_ONEDEAL                     1452
#define IDC_FINDSAME                    1452
#define IDC_ONEMINUTE                   1453
#define IDC_COMPDISCRIBE                1453
#define IDC_FIVEMINUTE                  1454
#define IDC_COMPNOTES                   1454
#define IDC_FIFTEENMINUTE               1455
#define IDC_COMPEDOLON                  1455
#define IDC_THIRTYMINUTE                1456
#define IDC_COMPSOURCE                  1456
#define IDC_SIXTYMINUTE                 1457
#define IDC_COMPALL                     1457
#define IDC_PERIOD_TYPE_DAY             1458
#define IDC_WEEK                        1459
#define IDC_MONTH                       1460
#define IDC_MOREDAY                     1461
#define IDD_COMPARE                     1465
#define IDC_COMCON1                     1465
#define IDC_DELAY_SEL                   1496
#define IDC_DLG_SEL                     1498
#define IDC_BLOKC_SEL                   1521
#define IDC_BEGIN_ALARM                 1529
#define IDC_BEGIN_ALARM2                1530
#define IDC_EXPTREE                     1557
#define IDC_IDEAPWD                     1565
#define IDC_WANT                        1566
#define IDC_ALLPWD                      1567
#define IDC_WRAN_CONDITION              1589
#define IDD_PERIOD_STATIC               1590
#define IDC_SELL_SEL                    1591
#define IDC_EIDOLON                     1637
#define IDB_BUTTON1                     1639
#define IDB_BUTTON2                     1640
#define IDD_CHANGEIN                    1654
#define IDD_PRESUCC                     1655
#define IDD_WRAN_ANALYSE                1747
#define IDC_COPY                        1748
#define IDC_STOB                        1794
#define IDD_NEWADD                      1797
#define IDD_NEWSET                      1798
#define IDD_TREE                        1802
#define IDD_AND_OR                      1805
#define IDC_STATIC10                    1805
#define IDC_STATIC4                     1806
#define IDD_HISDAY                      1808
#define IDD_TOBLOCK                     1811
#define IDD_CONNOTES                    1812
#define IDD_TOBLOCK2                    1813
#define IDD_GETNOWDATA                  1813
#define IDD_REPORT                      1814
#define IDD_PROMPT                      1815
#define IDC_HIDE                        1819
#define IDC_J_STK_SEL                   1822
#define IDC_T_SEL                       1823
#define IDC_INPUTCOUNT                  1834
#define IDC_STATICINPUT                 1835
#define IDC_STAITC6                     1836
#define IDC_STATIC6                     1836
#define IDC_COUNTIN                     1838
#define IDC_COMFOLLOW                   1839
#define IDC_SKIPCOUNT                   1840
#define IDC_DECOUNT                     1841
#define IDC_SINGLETEST                  1842
#define IDC_HOLETEST                    1843
#define IDC_MOSTBUY                     1845
#define IDC_MOSTCOUNT                   1846
#define IDC_LIMITCOUNT                  1847
#define IDC_SKIP                        1847
#define IDC_RANDOM                      1856
#define IDC_STATICDE                    1871
#define IDC_STATIC7                     1872
#define IDC_STAITCEMTY                  1873
#define IDC_BTOS                        1874
#define IDC_STATICLIMIT                 1888
#define IDC_STATICCOUNT                 1889
#define ID_MULITBUY                     1890
#define IDC_STATICOVERLOAD              1891
#define IDC_STATICGP                    1892
#define ID_MULITBUY2                    1893
#define IDC_STATIC3                     1895
#define IDC_BUTFUN                      7000
#define IDC_BUTEXP                      7001
#define IDR_INSERTEXPMENU               7001
#define IDR_INSERTFUNMENU               7002
#define IDD_PROMPTDLG                   7002
#define IDC_BUTFIND                     7003
#define IDD_BROWSEFORMULA               7003
#define IDC_BUTCOPY                     7005
#define IDD_INCLUDESTOCKANDTIMEDLG      7007
#define IDC_RADIO_OVR                   7008
#define IDD_BLOCK_ANALYSE               7008
#define IDC_RADIO_AUTONAME              7009
#define IDD_PIC_ANALYSE                 7009
#define IDC_RADIO_RETURN                7010
#define IDD_DIALOG1                     7010
#define IDD_UNITE_ANALYSE               7010
#define IDD_ADDPROJECT                  7011
#define IDC_POS                         7014
#define IDR_CHAGEPROJECT                7014
#define IDC_MIDDLE                      7015
#define IDR_UNITE_AYALYSE               7015
#define IDC_STATIC_CON                  7016
#define ID_Menu                         7016
#define IDC_COMBOGROUP                  7019
#define IDC_EXPGROUP                    7020
#define IDC_PARAMPOS                    7021
#define IDC_EDITPOS                     7022
#define ID_A7022                        7022
#define IDC_EDITDATECOUNT               7023
#define ID_Menu7023                     7023
#define IDC_BUTPARAM                    7024
#define IDC_BUTEXPRESS                  7025
#define IDC_BUTHIDELEFT                 7026
#define IDC_SELSTOCKRESULTPOS           7027
#define IDC_CONDITIONPOS                7028
#define IDC_BOTTOMPOS                   7029
#define IDC_EDITPARAM                   7030
#define IDC_EDITSELECTSTOCK             7032
#define IDC_SWITCHBUT                   7035
#define IDC_BEGIN_ANALYSE               7036
#define IDC_ADD_PROJECT                 7037
#define IDC_TAB1                        7038
#define IDC_LIST1                       7040
#define IDC_LIST_BOX                    7040
#define IDC_COMPLIST                    7040
#define IDC_COM_FORMAT                  7042
#define IDC_COM_TOTAL                   7043
#define IDC_COM_CYC                     7044
#define ID_EXIT                         7047
#define IDC_HISDATECHECK                7048
#define IDC_UNIONCHECK                  7049
#define IDC_DESC                        7051
#define IDC_EXPRESS                     7052
#define IDC_SELECT_EXPRESS              7053
#define IDC_SELECT_FUN                  7054
#define IDC_PIC                         7054
#define IDC_NEW_EXPRESS                 7054
#define IDC_BUTTON1                     7055
#define IDC_DEFAULT                     7055
#define IDC_SAVEAS                      7055
#define IDC_STARTBUTTON                 7055
#define IDC_ADD_CONDITION               7055
#define IDC_STATIC1                     7056
#define IDC_DEL_CONDITION2              7056
#define IDC_SAVE                        7056
#define IDC_KEYCOMBO                    7057
#define IDC_SAVEAS2                     7057
#define IDC_STOPBUT                     7059
#define IDC_FINDANIMATE                 7061
#define IDC_COMPEIDOLON                 7062
#define IDC_RESULTLIST                  7062
#define IDC_RESULTSTATIC                7065
#define IDC_COMPNAME                    7066
#define IDC_UNIONCOMBO                  7067
#define IDC_UNIONDLGPOS                 7068
#define IDC_EDITTOTALSTOCK              7069
#define ID_7070                         7070
#define IDC_LIST2                       7070
#define IDC_LIST3                       7071
#define IDC_CHAGE_PROJECT               7072
#define IDD_COMPFIND                    7073
#define IDC_CHAGE_PROJECT2              7073
#define IDCANCER                        7073
#define IDC_WRAN_ANALYSE                7074
#define IDD_SELECT                      7074
#define IDR_AVI1                        7075
#define IDC_CHAGE_PROJECT4              7075
#define IDC_EDIT1                       7076
#define IDC_EDIT2                       7077
#define IDD_TEMPUNION                   7077
#define IDC_EDIT3                       7078
#define IDD_TAILORSELECTSTOCK           7079
#define IDD_BEFOR_WARN                  7080
#define IDC_SPIN1                       7081
#define IDD_TECHDIALOG                  7081
#define IDD_INTELLIGENT_SELECT          7082
#define IDC_CHECK1                      7082
#define IDD_HISTORY_BLOCKANALYSE        7083
#define IDC_CHECK2                      7083
#define IDOKss                          7083
#define IDC_CHECK3                      7084
#define ID_M1_ANALYSE_CUR               7085
#define IDC_ISSTART                     7085
#define IDC_CHECK4                      7085
#define ID_M1_ANALYSE_ALL               7086
#define IDC_ALLDATA                     7086
#define ID_M1_EXIT                      7087
#define IDC_SAVE_PARAM                  7087
#define ID_M2_DEL                       7088
#define IDC_RECT_LIST                   7088
#define ID_M2_ADD                       7089
#define IDC_STOCKLIST                   7089
#define ID_M2_EDIT                      7090
#define ID_M2_EXIT                      7091
#define IDC_TAB2                        7091
#define IDC_TABOUT                      7091
#define IDD_DIALOG2                     7092
#define IDD_ALARM_PROPER                7092
#define IDB_RE_CACL                     7092
#define IDR_MENU2                       7093
#define IDR_ALARMMENU                   7093
#define IDB_SAVE                        7093
#define ID_ALARM1_BEGIN_ALL             7094
#define ID_ALARM1_END_ALL               7095
#define ID_ALARM1_BEGIN_CUR             7096
#define ID_ALARM1_END_CUR               7097
#define ID_ALARM1_EXIT                  7098
#define ID_ALARM1_CHG_CON               7099
#define ID_ALARM1_ADD_CON               7100
#define ID_ALARM1_DEL_CON               7101
#define ID_ALARM1_7103                  7103
#define ID_ALARM1_END                   7104
#define ID_ALARM1_BEGIN                 7105
#define IDC_CURSOR1                     7106
#define IDC_CHECK_CHUQUAN               7106
#define IDC_RADIO_DEFAULT               7106
#define IDB_BITMAP_ALARM                7107
#define IDC_RADIO_COMM                  7107
#define ID_ALARM1_7108                  7108
#define IDC_COMBO_CYCLE                 7108
#define ID_ALARM1_                      7109
#define IDC_BEGINDATE                   7109
#define IDD_DIALOG3                     7110
#define IDD_ADD_ALARM                   7110
#define IDC_ENDDATE                     7110
#define ID_ALARM2_DEL_CUR               7111
#define IDC_COMBO_OBJ                   7111
#define ID_ALARM2_DEL_ALL               7112
#define ID_ALARM2_EXIT                  7113
#define IDC_PROGRESS2                   7113
#define IDC_CACLPROGRESS                7113
#define ID_ALARM3_ADD                   7114
#define IDC_CHECK_ALLLOCTLDATA          7114
#define ID_ALARM3_START                 7115
#define IDC_CHECK_ALLSEL                7115
#define ID_ALARM3_EXIT                  7116
#define IDC_STATIC_NOTE                 7116
#define ID_ALARM3_CREATE                7117
#define IDC_STATICPROMPT                7117
#define IDC_CHECK_EXRIGHT               7118
#define IDD_EXCH_CACLTABLE              7120
#define IDC_BUTTON2                     7120
#define IDC_BUTTONCC                    7120
#define IDB_BITMAP1                     7121
#define IDB_EXCH_IMAGE                  7121
#define IDD_EXCHANGE_CACL_RESULT        7121
#define IDC_COMBO1                      7121
#define IDD_EXCH_PARAM                  7122
#define IDC_EDIT4                       7122
#define IDD_SEL_UNION_DLG               7123
#define IDC_EDIT5                       7123
#define IDD_EXCHAGNE_YOUSHUANG          7124
#define IDC_EDIT6                       7124
#define IDD_STOCKLIST                   7125
#define IDR_MENU1                       7125
#define IDR_EDITMAINMENU                7125
#define IDC_EDIT7                       7125
#define ID_7126                         7126
#define IDD_CONDITION_STOCK1            7126
#define IDD_CONDITION_STOCK_Auto        7126
#define IDC_COMBOPER                    7126
#define IDD_PERIOD_STATIC1              7127
#define IDD_PERIOD1                     7128
#define IDD_CONNOTES1                   7129
#define IDD_CON1                        7130
#define IDD_DIALOGStrategyHQ            7131
#define IDC_STATIC_CON1                 7131
#define IDD_COMPARE1                    7132
#define IDD_DIALOGStrategyMain          7133
#define IDD_DATA11                      7133
#define IDD_DIALOGStrategyTest          7134
#define IDD_AND_OR1                     7134
#define IDD_DATA21                      7135
#define IDC_MIDDLE1                     7136
#define IDD_STRATEGY_JY                 7136
#define IDC_NOTES1                      7137
#define IDC_BUTFIND1                    7138
#define IDD_DIALOG5                     7138
#define IDD_STRATEGY_TEST               7138
#define IDOK21                          7139
#define IDCANCEL31                      7140
#define IDC_RADIO11                     7141
#define IDC_RADIO21                     7142
#define IDD_TAB_STRATEGY_HQ             7142
#define IDC_RADIO31                     7143
#define IDD_DIALOGStgyMng               7145
#define IDC_DATETIMEPICKER2             7146
#define IDC_DATETIMEPICKER3             7147
#define IDC_DATETIMEPICKER4             7148
#define IDD_DIALOGSaveTrig              7148
#define IDC_DATETIMEPICKER5             7149
#define IDC_STATIC_UNIT                 7150
#define IDC_DATETIMEPICKERTIMEEND       7150
#define IDB_BITMAP2                     7150
#define IDC_STRATEGY_BUYTYPE            7151
#define IDD_DIALOG4                     7151
#define IDD_INFODATA                    7151
#define IDC_STRATEGY_BUYCOUNT           7152
#define IDD_DOWNLOADDATA                7152
#define IDC_CK_                         7153
#define IDC_CK_MAXGAIN                  7153
#define IDC_CK_MAXDEFICIT               7154
#define IDC_STRATEGY_GAIN               7155
#define IDC_STRATEGY_DEFICIT            7156
#define IDC_STRATEGY_FEES               7157
#define IDC_EDITGAP                     7158
#define IDC_CHECKFUQ                    7159
#define IDC_COMBO2                      7160
#define IDC_DATETIMEPICKERStart         7161
#define IDC_TABHQ                       7162
#define IDC_BUTTONOK                    7163
#define IDC_BUTTON3                     7164
#define IDC_TABHQ2                      7164
#define IDC_DATETIMEPICKEREnd           7165
#define IDC_COMBOCYCLE                  7166
#define IDC_EDITDAY                     7167
#define IDC_EDITBUY                     7168
#define IDC_EDITSELL                    7169
#define IDC_TABSTRATEGY                 7170
#define IDD_PERIOD_STATIC12             7171
#define IDD_PERIOD12                    7172
#define IDD_CON12                       7173
#define IDC_STATIC_CON12                7174
#define IDD_COMPARE12                   7175
#define IDD_DATA112                     7176
#define IDD_DATA212                     7177
#define IDC_MIDDLE2                     7178
#define IDC_EDITcode                    7179
#define IDC_COMBOcf                     7180
#define IDC_COMBOjy                     7181
#define IDC_CHECKxd                     7182
#define IDC_EDITMONEY                   7183
#define IDC_DATETIMEPICKERDAYStart      7184
#define IDC_DATETIMEPICKERDAYEND        7185
#define IDC_DATETIMEPICKERTIMESTART     7186
#define IDC_STRATEGYfee                 7187
#define IDC_BUTTONCANCEL                7189
#define IDC_BUTTONSAVE                  7190
#define IDC_BUTTONADD                   7191
#define IDC_LISTTRIG                    7192
#define IDC_BUTTONMODIFY                7193
#define IDC_BUTTONDELETE                7194
#define IDC_TABTrig                     7197
#define IDC_EDITNAME                    7199
#define IDC_STATICNAME                  7201
#define IDC_BUTTONTEST                  7202
#define IDC_STATICcf                    7203
#define IDC_RADIO01                     7204
#define IDC_RADIO02                     7205
#define IDC_RADIO03                     7206
#define IDC_BUTTONSV                    7207
#define IDC_BUTTONOPT                   7210
#define IDC_BUTTONBYDAY                 7211
#define IDC_DELETEUNION                 7219
#define IDC_TREE_DATATYPE               7220
#define IDC_BUTTON_YINCANG              7221
#define IDC_RADIO1                      7222
#define IDC_RADIO2                      7223
#define IDC_PROGRESS1                   7224
#define IDC_BUTTON4                     7225
#define IDC_BUTTON5                     7226
#define IDC_PAGEPOS                     10040
#define IDC_RECTGRID                    10078
#define IDC_SAVEASBLOCK                 10079
#define IDC_USERNOTES                   10080
#define IDC_ANALYSE                     10081
#define IDC_UNION_LIST                  10211
#define IDC_PAGE_DELETE                 10212
#define IDC_UNION_DELETE                10212
#define HS_IDR_MAINFRAME                28600
#define IDB_CLOSE                       28637
#define ID_MENUITEM32771                32771
#define IDM_DEFAULTPRESS                32771
#define ID_VIEW_FUN                     32772
#define ID_MENUITEM32772                32772
#define ID_VIEW_OUT                     32773
#define IDC_EDITPARAMLIST               32773
#define IDM_NOTES                       32774
#define IDC_EDITONLINEHELP              32774
#define IDM_EIDOLON                     32775
#define IDC_EDITRETURN                  32775
#define IDM_NEWGROUP                    32776
#define IDM_EXPANDGROUP                 32777
#define IDM_REDUCEGROUP                 32778
#define IDM_NEWEXPRESS                  32779
#define IDM_DELEXPRESS                  32780
#define IDM_EDITEXPRESS                 32781
#define IDM_DELGROUP                    32782
#define IDM_SAVE1                       32783
#define IDM_DELUINION                   32783
#define ID_PROJECTADD                   32784
#define ID_PROJECTCHAGE                 32785
#define ID_PROJECTDEL                   32786
#define ID_PICANALYSE                   32787
#define ID_MENUITEM32793                32793
#define IDM_PROPERTY                    32794
#define IDC_DESCRIBE                    32795
#define IDC_PERIOD                      32796
#define ID_POS                          32797
#define IDC_NAME1                       32798
#define IDC_MBYL                        32799
#define IDC_MAXLOSE                     32800
#define IDC_DOWN1                       32801
#define IDC_STATICZF                    32802
#define IDC_STATIC2                     32803
#define IDC_STAITCYUAN                  32804
#define ID_TESTM                        32805
#define IDC_STAITCYUAN2                 32805
#define ID_TESTOBJ                      32806
#define ID_TIMEPOS                      32807
#define ID_BUYPOS                       32808
#define ID_FOLLOWPOS                    32809
#define IDC_STATICTIME                  32810
#define IDC_STATIC9                     32811
#define IDC_STAITCCON                   32812
#define IDC_STATIC5                     32813
#define IDC_STATICFOLLOW                32814
#define IDC_EDIT_EXCH_PARAMSETBEGIN     40000
#define IDC_EDIT11                      40011
#define IDC_EDIT12                      40012
#define IDC_EDIT13                      40013
#define IDC_EDIT21                      40021
#define IDC_EDIT22                      40022
#define IDC_EDIT23                      40023
#define IDC_EDIT31                      40031
#define IDC_EDIT32                      40032
#define IDC_EDIT33                      40033
#define IDC_EDIT41                      40041
#define IDC_EDIT42                      40042
#define IDC_EDIT43                      40043
#define IDC_STATIC_EXCH_PARAMSETBEGIN   50000
#define IDC_STATIC11                    50011
#define IDC_STATIC12                    50012
#define IDC_STATIC13                    50013
#define IDC_STATIC21                    50021
#define IDC_STATIC22                    50022
#define IDC_STATIC23                    50023
#define IDC_STATIC31                    50031
#define IDC_STATIC32                    50032
#define IDC_STATIC33                    50033
#define IDC_STATIC41                    50041
#define IDC_STATIC42                    50042
#define IDC_STATIC43                    50043
#define IDR_MAINFRAME_ACCE              50090

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        7153
#define _APS_NEXT_COMMAND_VALUE         32787
#define _APS_NEXT_CONTROL_VALUE         7227
#define _APS_NEXT_SYMED_VALUE           7000
#endif
#endif
